# Generated by Django 5.0.1 on 2024-01-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeworksubmission',
            old_name='corrections',
            new_name='correct',
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='false',
            field=models.ManyToManyField(related_name='false', to='api.answer'),
        ),
    ]
