# Generated by Django 5.0.1 on 2024-01-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_corrections_homeworksubmission_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='correct',
            field=models.ManyToManyField(blank=True, null=True, related_name='corrections', to='api.answer'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='false',
            field=models.ManyToManyField(blank=True, null=True, related_name='false', to='api.answer'),
        ),
    ]
