# Generated by Django 5.0.1 on 2024-01-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_level_customuser_level_homework_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworksubmission',
            name='level',
        ),
    ]
