# Generated by Django 5.0.1 on 2024-01-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_homeworksubmission_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworksubmission',
            name='answers',
        ),
    ]
