# Generated by Django 5.0.1 on 2024-01-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_group_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
