# Generated by Django 5.0.1 on 2024-01-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(null=True, upload_to='images/groups/'),
        ),
    ]
