# Generated by Django 5.0.1 on 2024-02-02 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_communicate_group_alter_communicate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_communicate', to='api.groupmessages'),
        ),
        migrations.AlterField(
            model_name='communicate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
