# Generated by Django 5.0.1 on 2024-02-05 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_savedlist_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedlist',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_details', to='api.lesson'),
        ),
    ]
