# Generated by Django 5.0.1 on 2024-02-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_savedlist_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pp',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile-pictures/'),
        ),
    ]
